### ISSUE TITLE
Can't disable logger

### ISSUE THREAD

**Issue by KeiroMidori** [pubnub/objective-c#445]
Here's what I have in my app:

```
client.logger.enabled = false
client.logger.logLevel = .zero
client.logger.writeToFile = false
client.logger.writeToConsole = false
```

Here's what I see in my xcode console:
```
2023-03-14 11:06:31:041 <Logger::com.pubnub.pubnub-objc> Console logger enabled.
2023-03-14 11:06:31:041 <Logger::com.pubnub.pubnub-objc> File logger enabled.
2023-03-14 11:06:31:041 <Logger::com.pubnub.pubnub-objc> Log files stored in: /var/mobile/Containers/Data/Application/8151BFDB-F069-4C70-8738-345C7379B0EB/Documents/Logs/com.pubnub.pubnub-objc.
2023-03-14 11:06:31:041 <Logger::com.pubnub.pubnub-objc> Disk quota changed to 52428800 bytes.
```

By reading your code it looks like a `logLevel` set to 0 should disable the logger but your `log()` method does the opposite.
It's a simple mistake that can easily be fixed:

In the file `PNLLogger.m` you have the following line (639):
`if (self.enabled || level == 0)`

where it should be 
`if (self.enabled || level > 0)` or `if (self.enabled || level != 0)` or simply `if (self.enabled)` (considering that setting the `logLevel` to 0 will turn `enabled` to false)

Right now it's impossible to disable the logger without changing this line.

Thanks

**Comment by parfeon** [comment]
@KeiroMidori thank you for reaching out. 
It has been done intentional because we had few cases, where developers had issues but provided logs doesn't confirm it. Later we found out, that the developer ignored or forgot about our request to set the log level (was even cases when developer disabled the logger).

If the SDK used not from pre-compiled framework bundles, you can set `PUBNUB_DISABLE_LOGGER` under the `User-defined settings` section in the project's `Build Settings`.

**Comment by KeiroMidori** [comment]
@parfeon settings `PUBNUB_DISABLE_LOGGER` under `User-defined settings` doesn't work either. I tried setting it to `YES`, `NO`, and leaving it empty no matter what these logs will still show up.
<img width="810" alt="image" src="https://user-images.githubusercontent.com/3483761/225456265-bb94b2be-8896-452e-9630-c506b087ab42.png">

**Comment by parfeon** [comment]
@KeiroMidori how SDK integrated into your project: CocoaPods, from source, pre-compiled Frameworks (from release page or Carthage)?

**Comment by KeiroMidori** [comment]
CocoaPods

**Comment by parfeon** [comment]
Then that flag should be defined in Pods project, which actually compiles dependencies.
To make sure, that it will stay after `pod install` make changes in `Podfile`. For example::
```ruby
post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = '$(inherited) PUBNUB_DISABLE_LOGGER=1'
        end
    end
end
```
After `pod install` call changes should be applied to Pods project for PubNub target.

**Comment by KeiroMidori** [comment]
Indeed that makes more sense my bad 🤦🏼

It indeed worked. Is this macro specified in your documentation? I couldn't find it. If not it'd be a nice addition.
