### ISSUE TITLE
PNImports.h file not found

### ISSUE THREAD

**Issue by kamoljan** [pubnub/objective-c#89]
Hi guys

after upgrade PubNub to the latest version `3.7.10.6` in my CocoaPods:

    source 'https://github.com/CocoaPods/Specs.git'
    platform :ios, '8.0'
    use_frameworks!

    target 'ShoppingXXX' do
       pod 'Parse', '~> 1.7'
       pod 'ParseFacebookUtils', '~> 1.7'
       pod 'ParseCrashReporting', '~> 1.7'
       pod 'Facebook-iOS-SDK', '3.23.2'
       pod 'Bolts', '1.1.5'
       pod 'RBStoryboardLink', '0.1.4'
       pod 'PubNub', '3.7.10.6'
    end

I am getting `'PNImports.h' file not found` in my bridge file:

    #import <Bolts/Bolts.h>
    #import <Parse/Parse.h>
    #import <ParseFacebookUtils/PFFacebookUtils.h>
    #import <RBStoryboardLink/RBStoryboardLink.h>
    #import "PNImports.h" //<---- HERE

Any bug?

**Comment by vosovets** [comment]
Hi Kamol,

Thank you for reporting. It is already known issues with latest CocoaPods/Swift. We have made a fix and it will be available with next version: 3.7.10.7 in a day(as max -  two). I'll keep you updated when we release it.

Best Regards,
Vadim

**Comment by kamoljan** [comment]
Thank you, @vosovets !
We will be waiting for your release.

**Comment by kamoljan** [comment]
@vosovets any update?

**Comment by vosovets** [comment]
@kamoljan We are following pre-release testing procedure and today evening going to make a release.

**Comment by kamoljan** [comment]
@vosovets outstanding!

**Comment by vosovets** [comment]
@kamoljan `PubNub 3.7.10.8' has been pushed. Thank you for your patience.

**Comment by kamoljan** [comment]
@vosovets thank you, it works! :)

**Comment by kamoljan** [comment]
@vosovets sorry the issue is still there:

`PNImports.h' file not found`

Here is our `Podfile`:

    source 'https://github.com/CocoaPods/Specs.git'
    platform :ios, '8.0'

    use_frameworks!

    xcodeproj 'ShoppingXXX.xcodeproj'

    target 'ShoppingXXX' do
        pod 'Parse', '1.7.2'
        pod 'ParseFacebookUtils', '1.7.2'
        pod 'ParseCrashReporting', '1.7.2'
        pod 'Facebook-iOS-SDK', '3.23.2'
        pod 'Bolts', '1.1.5'
        pod 'RBStoryboardLink', '0.1.4'
        pod 'PubNub', '3.7.10.8'
    end

**Comment by vosovets** [comment]
@kamoljan Please use #import <PubNub/PNImports.h> instead of #import "PNImports.h".

**Comment by kamoljan** [comment]
@vosovets it works! Thank you!
