### ISSUE TITLE
Can't update sdk from COcoa pods any more

### ISSUE THREAD

**Issue by alexs555** [pubnub/objective-c#92]
While trying 'pod update' I receive error:  "Unable to satisfy the following requirements:  - PubNub (= 3.7.10.8) required by Podfile". pod search finds only version 3.7.10.1

**Comment by geremyCohen** [comment]
Strange... do you see 3.7.10.8 here? https://cocoapods.org/?q=pubnub

does setting:

pod 'PubNub', '~> 3.7'

work?

geremy

On Fri, May 22, 2015 at 12:16 AM, alexs555 <notifications@github.com> wrote:

> While trying 'pod update' I receive error: "Unable to satisfy the
> following requirements: - PubNub (= 3.7.10.8) required by Podfile". pod
> search finds only version 3.7.10.1
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/pubnub/objective-c/issues/92>.
>



-- 
Geremy Cohen
Director, Client Engineering
*PubNub*

**Comment by alexs555** [comment]
Looked like a cococapods bug. Completely uninstalled cocoapods, installed it again and everething is ok now.

**Comment by geremyCohen** [comment]
brute force approach :) glad to see you're up and running, feel free to
ping us at support@pubnub.com moving forward with any issues.

On Fri, May 22, 2015 at 1:22 AM, alexs555 <notifications@github.com> wrote:

> Looked like a cococapods bug. Completely uninstalled cocoapods, installed
> it again and everething is ok now.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/pubnub/objective-c/issues/92#issuecomment-104563188>.
>



-- 
Geremy Cohen
Director, Client Engineering
*PubNub*

**Comment by alexs555** [comment]
thanks guys, for your support and quick response. 22.05.2015, 20:24, "Geremy Cohen" <notifications@github.com>:brute force approach :) glad to see you're up and running, feel free to ping us at support@pubnub.com moving forward with any issues.  On Fri, May 22, 2015 at 1:22 AM, alexs555 <notifications@github.com> wrote:  > Looked like a cococapods bug. Completely uninstalled cocoapods, installed > it again and everething is ok now. > > -- > Reply to this email directly or view it on GitHub > <https://github.com/pubnub/objective-c/issues/92#issuecomment-104563188>. >    --  Geremy Cohen Director, Client Engineering *PubNub*—Reply to this email directly or view it on GitHub.   -- С уважением,Шпирко Алексей
