### ISSUE TITLE
Does character ":" (colon) has special meaning in the channel name?

### ISSUE THREAD

**Issue by mkll** [pubnub/objective-c#94]
PubNub documentation clearly says that channel name may consist of any UTF8 chars except ```,```, ```/```, ```\```. So, I tried to subscribe to ```@"Russia:Yakutsk"``` channel and got the following error message:

```
error=Domain=com.pubnub.pubnub; Code=118; Description="PubNub service can't process request"; Reason="Looks like target channel group is empty";
Fix suggestion="Try to add some channels to channel group before accessing it with other API";
Associated object=(
    "PNChannelGroup(0x7fbde24c0b70) Yakutsk in \"Russia\" namespace\nChannels: (null)"
)
```

But I'm not using namespaces and/or channel groups! The string above is just a channel name.

Then, I changed the channel name to ```@"Russia-Yakutsk"``` and subscription has completed successfully.

This is strange behavior while companion Android app works nicely with exactly the same channel name.

Could you point me to the wright direction on this?

**Comment by mkll** [comment]
Just found another piece of docs with the following:

*As for the channel name, you can use any characters you want except ```,```, ```/``` and ```:```, as they are reserved.*

There are no restrictions regarding use of ```:``` in Android SDK. Nice.

We run live Android project with thousand of users that use ```@"Country:City"``` channel naming convention, so we can't change this convention without impacting our users. And, now, what should we do in iOS counterpart of the project?

**Comment by mkll** [comment]
And yes, I discovered that ```PNChannel``` creates a group, not a channel, when he see the ```:``` in the channel name.

**Comment by geremyCohen** [comment]
Alex -

If this is impacting you please email us at support@pubnub.com and we can
get you a workaround.
geremy

On Fri, Jun 5, 2015 at 3:17 AM, Alex Sherbakov <notifications@github.com>
wrote:

> Closed #94 <https://github.com/pubnub/objective-c/issues/94>.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/pubnub/objective-c/issues/94#event-323423474>.
>



-- 
Geremy Cohen
Director, Client Engineering
*PubNub*

**Comment by mkll** [comment]
Geremy,

Thank you, the issue has been resolved by commenting out the appropriate fragment of ```PNChannel``` code.

**Comment by geremyCohen** [comment]
Ok, sounds good.

On Fri, Jun 5, 2015 at 11:00 AM, Alex Sherbakov <notifications@github.com>
wrote:

> Geremy,
>
> Thank you, the issue has been resolved by commenting out the appropriate
> fragment of PNChannel code.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/pubnub/objective-c/issues/94#issuecomment-109381451>.
>



-- 
Geremy Cohen
Director, Client Engineering
*PubNub*
